### PR TITLE
Make access to current element of builder public to allow use cases n…

### PR DESCRIPTION
**Pull request by berndruecker**
…ot properly supported by builder

### CODE REVIEW

**Comment by meyerdan** [comment]
Testcase(s) missing

**Comment by berndruecker** [comment]
What exact would you like to see in such a test case and what value would that add?? Have you had a look at the change?

**Comment by berndruecker** [comment]
@meyerdan I want to get this through this week - so if you need any test case let me know. So far I have no idea about the value of that test case, but if it helps to get that PR accepted might be worth adding one if you insist :-)

**Comment by meyerdan** [comment]
Usually, whenever we add public api we add at least a testcase which ensures that the api is "there" and does not get removed accidentally. But maybe not in this case, I am not sure. @menski ?

**Comment by menski** [comment]
@berndruecker if you have time just add a test case which ensures that an user can access the underlying element. So in case anyone things that the method should not be public in the future we have a failing test case, which implies that there was a reason to make the method public.

**Comment by berndruecker** [comment]
done

**Comment by menski** [comment]
I merged your changes with 972fb3a801fa2e0102943f5b2c043cbf21673d7b. Thanks again for your contribution.

For future pull requests please make sure to follow the [commit message guidelines](https://github.com/camunda/camunda-bpm-platform/blob/master/CONTRIBUTING.md#commit-message-conventions). And if it is required to update or extend the pull request it is common practice to squash all changes into a single commit. When you force push to your branch the pull request is automatically updated.

**Pull request closed without merging**
