### PR TITLE
feat(bpmn): add support for Data Store analogous to Data Object

### PR DESCRIPTION
**Pull request by falko**

### CODE REVIEW

**Comment by menski** [comment]
Hi Falko,

thanks for the pull request. But is there a reason why the DataStore interface is empty, although you implement the `itemSubjectRef` attribute. And it would be great if you also add the other attributes. Also please do not add test cases with asserts which are commented out.

Cheers,
Sebastian

**Comment by menski** [comment]
Hi @falko,

do you have any comment on my comment. Or are you planning to extend your pull request. Otherwise I will close this for now.

Cheers,
Sebastian

**Comment by menski** [comment]
Hi @falko,

I will close this pull request for now. Feel free to reopen it if you plan to improve it.

Cheers,
Sebastian

**Comment by falko** [comment]
Well, the intention of the pull request was to at least be able to load models that contain Data Store, not necessarily to comfortably work with all it's attributes. Without this pull request, parsing just fails. Thus, I copied what was there for Data Objects.

Under these circumstances, what would be the minimum needed to make the pull request acceptable?

**Comment by menski** [comment]
Hi Falko,

at least expose the attributes and child element getters and setters you implemented in the DataStore Interface. And do not add a test case with an assert which is commented out.

Cheers,
Sebastian

**Comment by falko** [comment]
Hi Sebastian,

I updated my pull request. The test is fixed by implementing all the missing Data Store attributes. The attributes itemSubject and dataState are inherited from the interface ItemAwareElement. I proved this by @Override annotations.

Cheers,
Falko

**Comment by menski** [comment]
Hi Falko,

thanks for implementing the remaining attributes, I merged it with 808e2c822462d87f1eb35f64d2bd32b9fb6a217c. Sorry I forgot about the ItemAwareElement.

I just fixed the DataStore attribute test as it now has more then one, and set the default value of the `isUnlimited` attribute to true as defined in the schema.

- https://github.com/camunda/camunda-bpmn-model/commit/808e2c822462d87f1eb35f64d2bd32b9fb6a217c#diff-2069a52e240652d3c846ac42cc02b47bR34
- https://github.com/camunda/camunda-bpmn-model/commit/808e2c822462d87f1eb35f64d2bd32b9fb6a217c#diff-df4d66f371c9796f98aa7e4fd27c568aR61

Cheers,
Sebastian

**Pull request closed without merging**
