### PR TITLE
feat (model): add convenience methods to allow using classes instead …

### PR DESCRIPTION
**Pull request by berndruecker**
…of class names only. fixes CAM-7564

### CODE REVIEW

**Comment by berndruecker** [comment]
Would be cool if this can make it in 7.7!

See also https://app.camunda.com/jira/browse/CAM-7564

**Comment by berndruecker** [comment]
Thanks!

**Comment by martinschimak** [comment]
👍 😄

**Comment by menski** [comment]
Ah sorry Bernd, I totally forgot to thank you for your contribution. :lollipop:

**Pull request merged**
